// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agents">> = Specific
  const handler = {} as typeof import("../../src/app/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/connected/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/connected">> = Specific
  const handler = {} as typeof import("../../src/app/connected/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/onboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboard">> = Specific
  const handler = {} as typeof import("../../src/app/onboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/teams/[teamId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teams/[teamId]">> = Specific
  const handler = {} as typeof import("../../src/app/teams/[teamId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/teams/join/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teams/join">> = Specific
  const handler = {} as typeof import("../../src/app/teams/join/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/teams/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teams">> = Specific
  const handler = {} as typeof import("../../src/app/teams/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent-state/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent-state">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent-state/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/[species]/[action]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/[species]/[action]">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/[species]/[action]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notion/connection/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notion/connection">> = Specific
  const handler = {} as typeof import("../../src/app/api/notion/connection/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notion/oauth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notion/oauth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/notion/oauth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notion/oauth/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notion/oauth/start">> = Specific
  const handler = {} as typeof import("../../src/app/api/notion/oauth/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notion/provision/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notion/provision">> = Specific
  const handler = {} as typeof import("../../src/app/api/notion/provision/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/team-chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/team-chat">> = Specific
  const handler = {} as typeof import("../../src/app/api/team-chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/teams/[teamId]/assign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/teams/[teamId]/assign">> = Specific
  const handler = {} as typeof import("../../src/app/api/teams/[teamId]/assign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/teams/[teamId]/invite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/teams/[teamId]/invite">> = Specific
  const handler = {} as typeof import("../../src/app/api/teams/[teamId]/invite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/teams/[teamId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/teams/[teamId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/teams/[teamId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/teams/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/teams/create">> = Specific
  const handler = {} as typeof import("../../src/app/api/teams/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/teams/join/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/teams/join">> = Specific
  const handler = {} as typeof import("../../src/app/api/teams/join/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/teams/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/teams/list">> = Specific
  const handler = {} as typeof import("../../src/app/api/teams/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
