// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/agents" | "/connected" | "/onboard" | "/teams" | "/teams/[teamId]" | "/teams/join"
type AppRouteHandlerRoutes = "/api/agent-state" | "/api/agent/[species]/[action]" | "/api/notion/connection" | "/api/notion/oauth/callback" | "/api/notion/oauth/start" | "/api/notion/provision" | "/api/team-chat" | "/api/teams/[teamId]" | "/api/teams/[teamId]/assign" | "/api/teams/[teamId]/invite" | "/api/teams/create" | "/api/teams/join" | "/api/teams/list"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/agents": {}
  "/api/agent-state": {}
  "/api/agent/[species]/[action]": { "species": string; "action": string; }
  "/api/notion/connection": {}
  "/api/notion/oauth/callback": {}
  "/api/notion/oauth/start": {}
  "/api/notion/provision": {}
  "/api/team-chat": {}
  "/api/teams/[teamId]": { "teamId": string; }
  "/api/teams/[teamId]/assign": { "teamId": string; }
  "/api/teams/[teamId]/invite": { "teamId": string; }
  "/api/teams/create": {}
  "/api/teams/join": {}
  "/api/teams/list": {}
  "/connected": {}
  "/onboard": {}
  "/teams": {}
  "/teams/[teamId]": { "teamId": string; }
  "/teams/join": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
